<a href="https://colab.research.google.com/github/Andresmup/recursos-analisis-datos/blob/dev/10_Numpy_2/Clase10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

## PARTE A

### Ejercicio 1.0

Importar los módulos necesarios

In [1]:
import math
import numpy as np

### Ejercicio 1.1

Calculemos el producto matricial, la matriz transpuesta y el determinante.

In [2]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

producto_matricial = np.matmul(matriz1, matriz2)
transpuesta = np.transpose(matriz1)
determinante = np.linalg.det(matriz1)

print("Producto matricial:")
print(producto_matricial)
print("Transpuesta de la matriz:")
print(transpuesta)
print("Determinante de la matriz:")
print(determinante)


Producto matricial:
[[19 22]
 [43 50]]
Transpuesta de la matriz:
[[1 3]
 [2 4]]
Determinante de la matriz:
-2.0000000000000004


### Ejercicio 1.2

Numpy tiene una función especifica para resolver ecuaciones lineales

In [3]:
coeficientes = np.array([[2, 3], [4, -1]])
constantes = np.array([5, 2])

solucion = np.linalg.solve(coeficientes, constantes)
print("Solución del sistema de ecuaciones:")
print("x =", solucion[0])
print("y =", solucion[1])

Solución del sistema de ecuaciones:
x = 0.7857142857142857
y = 1.1428571428571428


### Ejercicio 1.3

Exploremos funciones para conocer las dimensiones de un array multidimensional

In [4]:
array_multidimensional = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],
                                    [[0, 1, 2, 3],[4, 5, 6, 7]],
                                     [[0 ,1 ,2, 3],[4, 5, 6, 7]]])

In [5]:
array_multidimensional.ndim

3

In [6]:
array_multidimensional.size

24

In [7]:
array_multidimensional.shape

(3, 2, 4)

### Ejercicio 1.4

Veamos que posibilidades hay para indexar valores y separar un array

In [8]:
array_indexado = np.array([1, 2, 3, 4, 5, 6, 7])

In [9]:
array_indexado[0]

1

In [10]:
array_indexado[1]

2

In [11]:
array_indexado[0:2]

array([1, 2])

In [12]:
array_indexado[4:]

array([5, 6, 7])

In [13]:
array_indexado[-1:]

array([7])

### Ejercicio 1.5

Veamos como utilizar la funcion sort

In [14]:
array_desordenado = np.array([3, 1, 5, 2, 4])

array_ordenado = np.sort(array_desordenado)

array_ordenado

array([1, 2, 3, 4, 5])

### Ejericio 1.6

Ademas de ordernar un array podemos invertir el orden de los valores

In [15]:
array_original = np.array([1, 2, 3, 4, 11, 12, 13, 14, 15, 5, 6, 7, 8])

array_reverso = np.flip(array_original)
array_reverso

array([ 8,  7,  6,  5, 15, 14, 13, 12, 11,  4,  3,  2,  1])

### Ejercicio 1.7

Crear un array con numeros aleatorios

In [16]:
rng = np.random.default_rng()

In [17]:
rng.random(3)

array([0.90537163, 0.27359243, 0.90913706])

In [18]:
rng.integers(5, size=(2, 4))

array([[3, 0, 3, 4],
       [3, 2, 3, 3]])

### Ejercicio 1.8

Contar valores unicos dentro de un array

In [19]:
array_repetidos = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20, 11, 12, 13, 14, 15, 16, 17, 11, 14, 18, 19, 20])

array_unicos= np.unique(array_repetidos)
array_unicos

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Parte A

Tenemos una función cúbica con la forma (3*x^3-7*x^2+6*x+9)

In [20]:
def mi_funcion(x):
    return 3 * x**3 - 7 * x**2 + 6 * x + 9

### Ejercicio 2.1

Calcular cuales serian los valores obtenidos al pasarle como argumentos los valores pares desde 0 a 20 incluyendo ambos. Guardar el resultado en un array.

In [21]:
lista_valores_x = []
for i in range(0, 21, 2):
    lista_valores_x.append(i)
input_array = np.array(lista_valores_x)
input_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
output_array = mi_funcion(input_array)
output_array

array([    9,    17,   113,   441,  1145,  2369,  4257,  6953, 10601,
       15345, 21329])

### Ejercicio 2.2

Al array que obtuvimos en la sección anterior:

*   Calcula la media de los números en el array que contiene los valores calculados.
*   Calcula la desviación estándar de los números en el array calculado.
*   Encuentra el valor máximo y su índice en el array calculado.
*   Crea un nuevo array array_cuadrados que contenga el cuadrado de cada número en calculado.
*   Crear un array con la suma acumulativa (a1, a1+a2, a1+a2+a3, .....) de los elementos en array_cuadrados.
*   Crear un array con la raiz 5ta de cada valor de array_cuadrados (redondear a 2 decimales).




Imprimir los resultados obtenidos.

In [23]:
media = np.mean(output_array)

desviacion_estandar = np.std(output_array)

valor_maximo = np.max(output_array)

indice_maximo = np.argmax(output_array)

array_cuadrados = np.square(output_array)

suma_acumulativa_cuadrados = np.cumsum(array_cuadrados)

array_raiz_quinta = np.power(array_cuadrados, 1/5).round(2)

print("Media:", media)
print("Desviación Estándar:", desviacion_estandar)
print("Valor Máximo:", valor_maximo)
print("Índice del Valor Máximo:", indice_maximo)
print("Valores al Cuadrado:", array_cuadrados)
print("Array Suma Acumulativa de Valores al Cuadrado:", suma_acumulativa_cuadrados)
print("Array Resultado Raiz Quinta:", array_raiz_quinta)

Media: 5689.0
Desviación Estándar: 6877.906658279102
Valor Máximo: 21329
Índice del Valor Máximo: 10
Valores al Cuadrado: [       81       289     12769    194481   1311025   5612161  18122049
  48344209 112381201 235469025 454926241]
Array Suma Acumulativa de Valores al Cuadrado: [       81       370     13139    207620   1518645   7130806  25252855
  73597064 185978265 421447290 876373531]
Array Resultado Raiz Quinta: [ 2.41  3.11  6.63 11.42 16.73 22.38 28.29 34.42 40.75 47.25 53.9 ]


### Ejercicio 2.3

Con los arrays que obtuvimos en la sección anterior:

*   Calcular el producto escalar (o producto punto) entre los array output y el array raiz quinta.
*   Crear un vector con los 3 ultimos valores del array input. Crear un segundo vector con los 3 primeros valores del array suma acumulativa de los cuadrados. Calcular el array que daria como resultado hacer el producto vectorial entre ambos.

In [24]:
resultado_producto_escalar = np.matmul(output_array,array_raiz_quinta).round(2)
resultado_producto_escalar

2744461.93

In [25]:
vector1 = input_array[-3:]
vector2 = suma_acumulativa_cuadrados[:3]
resultado_producto_vectorial = np.cross(vector1,vector2)
resultado_producto_vectorial

array([ 229102, -208604,    4462])